name: Update versions in source template

on:
  schedule:
    - cron:  '3 3 3 * *'  # 3:03 on the 3rd of each month

jobs:
  update-template:
    if: github.repository == 'alan-turing-institute/ARC-project-template'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install poetry
        run: |
          curl -sSL https://install.python-poetry.org | python3 -
          poetry self add poetry-plugin-up

      - name: Update poetry dependencies
        run: poetry up --latest

      - name: Install poetry dependencies
        run: poetry install

      - name: Update pre-commit hooks
        run: poetry run pre-commit autoupdate

      - name: Push changes 
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          add_options: '-u'
          commit_message: ':arrow_up: Update poetry and pre-commit dependencies'
